name: Update Content Submodule

on:
  schedule:
    - cron: '0 0 * * *'  # Trigger the workflow daily, adjust the schedule as needed

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update submodule
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "Update content submodule"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
